import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "VRV-Frontend",
  description: "Generated by Killer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
